### PR TITLE
[libshortfin] Add missing scheduler dependency.

### LINKED ISSUE #178: [libshortfin] Subprocess example tests spuriously fail
tests/examples/async_test.py subprocesses randomly/spuriously fail with an ABORT. In debug python builds, this manifests as an assert on some low level IO code trying to write to stdout. In production builds, it just aborts. We sometimes see corrupted output from these tests too (unprintable characters that show up in logs).

Marking as skip with a reference to this bug so we can see when it is happening without blocking the build.

### PR DESCRIPTION
**Pull request by stellaraccident**
As written, command buffers could be scheduled out of order (with signal < deps). We need a more enlightened scheduler soon, but for the moment, this makes it correct.

Also sets the IREE runtime IREE_TASK_SCOPE_FLAG_ABORT_ON_FAILURE in debug builds, which will cause an eager assert-like crash. Since in our usage, this is always a critical error, it makes sense to treat it like an assert (and I would like to add finer grained control in the future). In release builds, it will propagate as a soft error, but it is basically fatal as it will lock the accounting structures into a persistent error state.

Fixes #178

### CODE REVIEW

File: libshortfin/src/shortfin/local/systems/host.cc [hunk 1]
```diff
@@ -26,6 +26,16 @@ HostCPUSystemBuilder::Deps::Deps(iree_allocator_t host_allocator) {
   iree_task_executor_options_initialize(&task_executor_options);
   iree_hal_task_device_params_initialize(&task_params);
   iree_task_topology_initialize(&task_topology_options);
+
+#ifndef NDEBUG
```
Comment (benvanik) [inline libshortfin/src/shortfin/local/systems/host.cc:30]: good idea

**Review by benvanik — APPROVED** [review]

File: libshortfin/src/shortfin/local/systems/host.cc (hunk 1 above)
Comment (stellaraccident) [reply libshortfin/src/shortfin/local/systems/host.cc:30]: I usually hate those kind of add-ons to NDEBUG, but for us, this really is like an assert so feel ok about it.
